---
- name: EPEL and SCL repository installed
  yum:
    name: epel-release, centos-release-scl
  tags: packages

- name: YUM requirements
  yum:
    name: "{{ item }}"
    state: "{{ yum_state | default('present') }}"
  with_items:
  - python-virtualenv # Seeder
  - python-devel # Seeder: psycopg2
  - postgresql-devel # Seeder: psycopg2
  - python-psycopg2 # Seeder
  - mysql-devel # Seeder: psycopg2
  - libjpeg-turbo-devel # Seeder: Pillow
  - zlib-devel # Seeder: Pillow
  - gcc # Seeder: Pillow
  - libfonts # Manet: Phantom.js dependency
  - uwsgi 
  - uwsgi-plugin-python
  - uwsgi-plugin-python3
  - python34
  - python34-devel
#  - rh-python35
  - python-pip
  - memcached
  - policycoreutils-python # SELinux module for Ansible
  tags: packages

- name: virtualenv upgraded to latest
  pip:
    name: "virtualenv"
    state: "latest"
  tags: packages

- name: requirements.txt satisfied in virtualenv {{ seeder_virtualenv }}
  pip:
    requirements: "{{ seeder_home }}/{{ item }}"
    virtualenv: "{{ seeder_virtualenv }}"
    state: latest
    virtualenv_python: python3.4
  with_items:
  - requirements.txt
#  - "requirements_dev.txt"
  tags: update
#  environment:
#    PATH: /opt/rh/rh-python35/root/usr/bin:{{ ansible_env.PATH }}
#    LD_LIBRARY_PATH: /opt/rh/rh-python35/root/usr/lib64
#    XDG_DATA_DIRS: /opt/rh/rh-python35/root/usr/share:/usr/local/share:/usr/share
#    PKG_CONFIG_PATH: /opt/rh/rh-python35/root/usr/lib64/pkgconfig
#  vars:
#    ansible_python_interpreter: /opt/rh/rh-python35/root/bin/python3.5

- name: seeder longs for mysqlclient too
  pip:
    name: "{{ item }}"
    virtualenv: "{{ seeder_virtualenv }}"
    state: "latest"
    virtualenv_python: python3.4
  with_items:
  - "mysqlclient"
  tags: packages
#  environment:
#    PATH: /opt/rh/rh-python35/root/usr/bin:{{ ansible_env.PATH }}
#    LD_LIBRARY_PATH: /opt/rh/rh-python35/root/usr/lib64
#    XDG_DATA_DIRS: /opt/rh/rh-python35/root/usr/share:/usr/local/share:/usr/share
#    PKG_CONFIG_PATH: /opt/rh/rh-python35/root/usr/lib64/pkgconfig
#  vars:
#    ansible_python_interpreter: /opt/rh/rh-python35/root/bin/python3.5

# There is bug in Ansible now
#- name: seeder wants analysis-icu plugin for elasticsearch
#  elasticsearch_plugin: 
#    name: "analysis-icu"
#    state: "present"
#  tags: elastic
#  notify: restart elasticsearch
#
# WORKAROUND
#
...
