- name: restart uwsgi
  service: name="uwsgi" state="started" enabled="yes"

- name: start uwsgi
  service: name="uwsgi" state="restarted" enabled="yes"

- name: reload uwsgi
  service: name="uwsgi" state="reloaded"

- name: restart memcached
  service: name="memcached" state="restarted" enabled="yes"

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: reload nginx
  service:
    name: nginx
    state: reloaded
